domain-include: virl.info
ignore-invalid-commands: true
crawl: true
auth-break: false
connection-types:
  - ssh
  - telnet
site-name: test
customer-name: FAKE COMPANY PTY LTD
ucdin: '91218238123'
devices:
  - 172.16.1.81-82
scan:
  timeout: 3
  count: 3
  interval: 0.5
  batch-size: 10
multi-process: false
inventory-merge: 'null'
