columns:
  Host_Name: "{{ HostName[0]}}"
  UCIDN: ""
  Customer_Name: ""
  Device_IP: "{{ DeviceIP }}"
  Device_FQDN: "{{DeviceFQDN}}"
  Device_Type: "{{DeviceType}}"
  Device_Vendor: "{{DeviceVendor}}"
  Device_Model: "{{ DeviceModel[1] }}"
  Device_Location: "{{ DeviceLocation[0] }}"
  Serial_Number: "{{ SerialNumber[0] }}"
  Uptime: "{{Uptime}}"
  Module_Name: "{{ModuleName}}"
  Module_Description: "{{ModuleDescription}}"
  Module_PartNo: "{{ModulePartNo}}"
  Module_Serial: "{{ModuleSerial}}"
  Module_Names: "{{ModuleNames}}"
  Module_Descriptions: "{{ModuleDescriptions}}"
  Module_PartNos: "{{ModulePartNos}}"
  Module_Serials: "{{ModuleSerials}}"
  Idprom_Serials: "{{IdpromSerials}}"
  Idprom_Models: "{{IdpromModels}}"
  Run_Date: "{{RecordDate}}"
pdf:
  report-extractions:
    ReportTimestamp:
      records:
        - starttime:timestamp
      command: "{{ starttime.strftime('%c') }}"
    Runtime:
      records:
        - starttime:timestamp
        - endtime:timestamp
      command: "{{ get_duration(starttime, endtime) }}"
    DevicesSuccessful:
      records:
        - succeeded
      command: "{{ succeeded | length }}"
    DevicesFailed:
      records:
        - failed
      command: "{{ failed | length }}"
    TotalDevices:
      records:
        - succeeded
        - failed
      command: "{{ (succeeded | length + failed | length) }}"
  graphs:
    - graph_devices_type_breakdown
    - graph_devices_vendor_breakdown
    - graph_devices_model_breakdown
    - graph_devices_location_breakdown
    - graph_device_types_location_breakdown
  records:
    # do not change the name of the keys
    ReportName: ""
    SiteName: ""
    ReportTimestamp: "{{ ReportTimestamp }}"
    Runtime: "{{ Runtime }}"
    TotalDevices: "{{ TotalDevices }}"
    DevicesSuccessful: "{{ DevicesSuccessful }}"
    DevicesFailed: "{{ DevicesFailed }}"
